/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aquamind.tracker;

import com.mycompany.aquamind.Menu;
import com.mycompany.aquamind.auth.AuthUi;
import com.mycompany.aquamind.tracker.TrackerManager;
import com.mycompany.aquamind.user.user;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Habit UI
 * @author Kripa Shrestha
 */
public class HabitUI extends javax.swing.JFrame {
    private TrackerManager trackerManager;
    private user currentUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HabitUI.class.getName());

    /**
     * Creates new form HabitUI
     */
    public HabitUI(user loggedInUser) {
        this.currentUser = loggedInUser;
        trackerManager = new TrackerManager(currentUser);
        initComponents();
    }

    private HabitUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTap = new javax.swing.JCheckBox();
        cbShower = new javax.swing.JCheckBox();
        cbLaundry = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        lblHabitTracker = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnHome = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setPreferredSize(new java.awt.Dimension(389, 500));

        cbTap.setText("Turn off tap while brushing");

        cbShower.setText("Take shorter showers");

        cbLaundry.setText("Run full laundry loads");

        btnSave.setBackground(new java.awt.Color(102, 255, 204));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHabitTracker.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblHabitTracker.setForeground(new java.awt.Color(0, 204, 204));
        lblHabitTracker.setText("Habit Tracker");

        btnHome.setBackground(new java.awt.Color(0, 204, 153));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBack2.setBackground(new java.awt.Color(153, 204, 255));
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnSave)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnHome)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHabitTracker)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbShower)
                            .addComponent(cbLaundry)
                            .addComponent(cbTap))
                        .addGap(114, 114, 114))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnBack2)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblHabitTracker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTap)
                .addGap(21, 21, 21)
                .addComponent(cbShower)
                .addGap(21, 21, 21)
                .addComponent(cbLaundry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(281, Short.MAX_VALUE)
                    .addComponent(btnBack2)
                    .addGap(16, 16, 16)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Save Button Action
     *  
     */
    // Called from btnSaveActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ArrayList<Habit> habits = trackerManager.getHabits();

    // Update habit completion based on checkboxes
        for (Habit h : habits) {
            switch (h.getName().toLowerCase()) {
                case "turn off tap while brushing": 
                    h.setCompleted(cbTap.isSelected());
                    break;
                case "take shorter showers": 
                    h.setCompleted(cbShower.isSelected());
                    break;
                case "run full laundry loads": 
                    h.setCompleted(cbLaundry.isSelected());
                    break;
            }
        }

        // Save to CSV directly using BufferedWriter
        String filename = "habits_" + currentUser.getUsername() + ".csv";
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filename))) {
            for (Habit h : habits) {
                bw.write(h.getName() + "," + h.isCompleted());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "Progress saved!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving habits: " + e.getMessage(), "Save Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new AuthUi().setVisible(true); //Opens Auth UI
        this.dispose(); //Closes Habit UI
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        new Menu().setVisible(true); //Back to Menu
        this.dispose(); //Closes HabitUI
    }//GEN-LAST:event_btnBack2ActionPerformed

    /**
     * Main Method for testing UI
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        user testUser = new user("TestUser", "test@example.com", "password123"); //dummy user for testing
        java.awt.EventQueue.invokeLater(() -> new HabitUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbLaundry;
    private javax.swing.JCheckBox cbShower;
    private javax.swing.JCheckBox cbTap;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lblHabitTracker;
    // End of variables declaration//GEN-END:variables
}
