/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aquamind.tracker;

import javax.swing.JOptionPane;
import javax.swing.*;
import com.mycompany.aquamind.AquaMindApp;
import com.mycompany.aquamind.Menu;

/**
 *
 * @author Kripa Shrestha
 */
public class TrackerUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrackerUI.class.getName());

    /**
     * Creates new form TrackerUI
     */
    public TrackerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtShower = new javax.swing.JTextField();
        txtLaundry = new javax.swing.JTextField();
        txtSink = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        cbTap = new javax.swing.JCheckBox();
        cbShower = new javax.swing.JCheckBox();
        cbLaundry = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblHabitTracker = new javax.swing.JLabel();
        lblWaterCalc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Shower (mins)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Laundry (loads)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Sink (mins)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        txtShower.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtShower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowerActionPerformed(evt);
            }
        });
        getContentPane().add(txtShower, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 20));

        txtLaundry.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        getContentPane().add(txtLaundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, 20));

        txtSink.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtSink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinkActionPerformed(evt);
            }
        });
        getContentPane().add(txtSink, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 20));

        btnCalculate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        btnReset.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        lblResult.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblResult.setText("Estimated daily use: 0 L");
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        cbTap.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbTap.setText("Turn off tap while brushing");
        getContentPane().add(cbTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        cbShower.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbShower.setText("Take shorther showers");
        getContentPane().add(cbShower, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        cbLaundry.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbLaundry.setText("Run full laundry loads");
        getContentPane().add(cbLaundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        btnSave.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 450, -1));

        lblHabitTracker.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblHabitTracker.setText("Habit Tracker");
        getContentPane().add(lblHabitTracker, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        lblWaterCalc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblWaterCalc.setText("Water Usage Calculator");
        getContentPane().add(lblWaterCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtShowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowerActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try{
            double shower = Double.parseDouble(txtShower.getText());
            int laundry = Integer.parseInt(txtLaundry.getText());
            double sink = Double.parseDouble(txtSink.getText());
            
            TrackerManager manager = new TrackerManager();
            double result = manager.calculateDailyUse(shower, laundry, sink);
            
            lblResult.setText("Estimated daily use:" +result+ " L");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter vaild numbers!");
            
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtSinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinkActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JOptionPane.showMessageDialog(this, "Progress saved!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtShower.setText("");
        txtLaundry.setText("");
        txtSink.setText("");
        lblResult.setText("Estimated daily use: 0 L");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrackerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbLaundry;
    private javax.swing.JCheckBox cbShower;
    private javax.swing.JCheckBox cbTap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHabitTracker;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblWaterCalc;
    private javax.swing.JTextField txtLaundry;
    private javax.swing.JTextField txtShower;
    private javax.swing.JTextField txtSink;
    // End of variables declaration//GEN-END:variables
}
