/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aquamind.EduQuizView;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class AddNewQuestionFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewQuestionFrame.class.getName());

    private int generateId() {
        File file = new File("Questions.txt");

        // if the file dont exist, will start at 1
        if (!file.exists()) {
            return 1;
        }

        int lastId = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("ID:")) {
                    lastId = Integer.parseInt(line.replace("ID:", "").trim());
                }
            }
        } catch (Exception e) {
        }

        return lastId + 1;
    }

    /**
     * Creates new form AddNewQuestionFrame
     */
    public AddNewQuestionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        questionIdLabel = new javax.swing.JLabel();
        idQuestion = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        option1 = new javax.swing.JLabel();
        option2 = new javax.swing.JLabel();
        option3 = new javax.swing.JLabel();
        option4 = new javax.swing.JLabel();
        Answer = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jTextFieldOption1 = new javax.swing.JTextField();
        jTextField3Option2 = new javax.swing.JTextField();
        jTextField4Option3 = new javax.swing.JTextField();
        jTextField5Option4 = new javax.swing.JTextField();
        jTextField6Anwer = new javax.swing.JTextField();
        jButton1Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 255, 255));
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 64, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("add new Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 6, 478, -1));

        closeBtn.setBackground(new java.awt.Color(204, 0, 51));
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 1054, 10));

        questionIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        questionIdLabel.setText("Question ID: ");
        getContentPane().add(questionIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        idQuestion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        idQuestion.setForeground(new java.awt.Color(255, 255, 255));
        idQuestion.setText("00");
        getContentPane().add(idQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 37, -1));

        questionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        questionLabel.setText("Question:");
        getContentPane().add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 151, 93, -1));

        option1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        option1.setText("Option 1:");
        getContentPane().add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 206, -1, -1));

        option2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        option2.setText("Option 2:");
        getContentPane().add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 261, -1, -1));

        option3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        option3.setText("Option 3: ");
        getContentPane().add(option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 310, 93, -1));

        option4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        option4.setText("Option 4:");
        getContentPane().add(option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 365, -1, -1));

        Answer.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Answer.setText("Answer:");
        getContentPane().add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 420, 88, -1));

        jTextFieldQuestion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 146, 623, -1));

        jTextFieldOption1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 201, 623, -1));

        jTextField3Option2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextField3Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 256, 623, -1));

        jTextField4Option3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextField4Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 305, 623, -1));

        jTextField5Option4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextField5Option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 360, 623, -1));

        jTextField6Anwer.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextField6Anwer, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 415, 623, -1));

        jButton1Save.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton1Save.setText("Save");
        jButton1Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 479, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SaveActionPerformed
        new Thread(() -> {
            int id = generateId();
            idQuestion.setText(String.valueOf(id));

            String question = jTextFieldQuestion.getText();
            String option1Question = jTextFieldOption1.getText();
            String option2Question = jTextField3Option2.getText();
            String option3Question = jTextField4Option3.getText();
            String option4Question = jTextField5Option4.getText();
            String answer = jTextField6Anwer.getText();

            String content
                    = "ID: " + id + "\n"
                    + "Question: " + question + "\n"
                    + "Option 1: " + option1Question + "\n"
                    + "Option 2: " + option2Question + "\n"
                    + "Option 3: " + option3Question + "\n"
                    + "Option 4: " + option4Question + "\n"
                    + "Answer: " + answer + "\n\n";

            try (FileWriter writer = new FileWriter("Questions.txt", true)) {
                writer.write(content);
            } catch (IOException ex) {
                SwingUtilities.invokeLater(()
                        -> JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage()));
                return;
            }

            SwingUtilities.invokeLater(()
            
               -> JOptionPane.showMessageDialog(null, "Saved successfully!"));
            
            QuizAdminFrame adminFrame = new QuizAdminFrame();
            adminFrame.setVisible(true);
            
             this.dispose();
            
            
        }).start();
        
        
    }//GEN-LAST:event_jButton1SaveActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewQuestionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel idQuestion;
    private javax.swing.JButton jButton1Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3Option2;
    private javax.swing.JTextField jTextField4Option3;
    private javax.swing.JTextField jTextField5Option4;
    private javax.swing.JTextField jTextField6Anwer;
    private javax.swing.JTextField jTextFieldOption1;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JLabel option1;
    private javax.swing.JLabel option2;
    private javax.swing.JLabel option3;
    private javax.swing.JLabel option4;
    private javax.swing.JLabel questionIdLabel;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
